OV-99: update loader
BinaryStudioAcademy/bsa-2024-outreachvids pull request #107
Opened 2024-08-31 08:27 UTC by sergiy4

This PR fixes the overlay component

2024-09-02 07:42 UTC, o-nedashkivska submitted a review, later dismissed

2024-09-02 11:00 UTC, nikita-remeslov approved these changes

2024-09-02 11:00 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/overlay/overlay.tsx
> +            }}
move to `styles.module.css`

2024-09-02 11:00 UTC, nikita-remeslov requested changes
check my comment

2024-09-05 09:54 UTC, o-nedashkivska approved these changes

2024-09-05 11:35 UTC, o-nedashkivska approved these changes

2024-09-05 11:40 UTC, nikita-remeslov approved these changes

2024-09-05 11:40 UTC, merged