OV-126:  Update ProtectedRoute to redirect to Sign-In page if no token exists
BinaryStudioAcademy/bsa-2024-outreachvids pull request #129
Opened 2024-09-02 15:54 UTC by o-nedashkivska

Related issue - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/126

2024-09-02 18:55 UTC, Sanchousina commented
But why can't you just check for the user from the auth slice? If the token exists, after loadCurrentUser is fulfilled, there will be a user  object in the auth slice, and if there is no token, then the user will remain null

2024-09-02 19:02 UTC, o-nedashkivska commented
> But why can't you just check for the user from the auth slice? If the token exists, after loadCurrentUser is fulfilled, there will be a user object in the auth slice, and if there is no token, then the user will remain null

Because when ProtectedRoute component is rendered user is null and dataStatus='idle' in both cases when token exists or not. Of course I can show loader while dataStatus is 'idle', but if request will not be made because token does not exists it will be infinite loader.

2024-09-02 19:17 UTC, WilsonBravo approved these changes

2024-09-03 01:43 UTC, JKaypa reviewed
But user should be still checked, and not only rely on token, because it should be corrupted or expired, and then an unauthorized user can enter the app.

2024-09-03 01:49 UTC, JKaypa requested changes
Token should be validated only on backend, and if response is successful redirect to home page

2024-09-03 06:25 UTC, anton-otroshchenko commented
Looks like it was already done here #119

2024-09-03 06:48 UTC, o-nedashkivska commented
This pr will solve the issue https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/119

2024-09-03 06:48 UTC, closed without merging