OV-133: Add-user-name
BinaryStudioAcademy/bsa-2024-outreachvids pull request #134
Opened 2024-09-02 21:24 UTC by JKaypa

Get fullName from store and add it to user card, then get initials from it and add it to user avatar. If no name is provided placeholder is rendered

2024-09-02 21:26 UTC, JKaypa commented
![image](https://github.com/user-attachments/assets/b510e69a-1286-4dde-a47f-07a1971cbc73)
![image](https://github.com/user-attachments/assets/6852c37e-2655-4dda-ba4b-daed50ee3131)

2024-09-03 07:22 UTC, o-nedashkivska commented on frontend/src/bundles/users/components/user-card/components/user-avatar.tsx
> +    const { user } = useAppSelector(({ auth }) => auth);
```suggestion
   const { user } = useAppSelector(({ auth }) => ({
      user: auth.user,
   }));
```
We are using it like this everywhere, so I guess it is better to be consistent with our code style

2024-09-03 07:22 UTC, o-nedashkivska commented on frontend/src/bundles/users/components/user-card/helpers/get-initials.helper.ts
> +        const secondInitial = splittedName[1]?.charAt(0).toUpperCase() ?? '';
```suggestion
        const [firstName, lastName] = fullName.trim().split(/\s+/);
        const firstInitial = firstName?.charAt(0).toUpperCase();
        const secondInitial = lastName?.charAt(0).toUpperCase() ?? '';
```

2024-09-03 08:20 UTC, o-nedashkivska commented on frontend/src/bundles/users/components/user-card/components/user-avatar.tsx
Please, do not remove `username` prop from UserAvatar component because it will be used not only in the sidebar, but also in chat component https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/82
In parent component just get username from store and pass it here as prop

2024-09-03 11:54 UTC, JKaypa commented on frontend/src/bundles/users/components/user-card/components/user-avatar.tsx
But, it already has the username initials from the store. Why is it necessary to pass props everywhere this component is needed?

2024-09-03 11:56 UTC, o-nedashkivska commented on frontend/src/bundles/users/components/user-card/components/user-avatar.tsx
Because Luis is also using UserAvatar for 'AI user' in Chat component

2024-09-03 13:03 UTC, JKaypa commented on frontend/src/bundles/users/components/user-card/components/user-avatar.tsx
Yes, I already noticed it

2024-09-03 14:46 UTC, sofiia-trokhymchuk requested changes

2024-09-03 14:46 UTC, sofiia-trokhymchuk commented on frontend/src/bundles/users/components/user-card/helpers/get-initials.helper.ts
> +export { getInitials };
Consider using early return for better readability
```suggestion
const getInitials = (fullName: string | undefined): string => {
    if (!fullName) {
        return 'FN';
    }
    
    const [firstName, lastName] = fullName.trim().split(/\s+/);
    const firstInitial = firstName?.charAt(0).toUpperCase();
    const secondInitial = lastName?.charAt(0).toUpperCase() ?? '';

    return `${firstInitial}${secondInitial}`;
};

export { getInitials };
```

2024-09-03 21:27 UTC, anton-otroshchenko approved these changes

2024-09-05 10:20 UTC, o-nedashkivska approved these changes

2024-09-06 13:44 UTC, sofiia-trokhymchuk approved these changes

2024-09-06 13:53 UTC, merged