OV-135: Convert-fa-icons
BinaryStudioAcademy/bsa-2024-outreachvids pull request #136
Opened 2024-09-02 23:10 UTC by JKaypa

Convert fa icons to Chakra Icons type, remove unnecessary as={FontAweseomeicon} property in all codebase

2024-09-05 10:21 UTC, o-nedashkivska commented
Please, fix conflicts

2024-09-06 23:12 UTC, o-nedashkivska commented on frontend/src/bundles/studio/components/video-menu/components/mock/menu-mock.tsx
> +const ScriptContent: React.FC = () => <div>This is the Script content.</div>;
We don't need this mocked data for scripts, it is not used in the project anymore

2024-09-09 08:55 UTC, o-nedashkivska commented on frontend/src/bundles/studio/components/video-menu/components/mock/menu-mock.tsx
> +const ScriptContent: React.FC = () => <div>This is the Script content.</div>;
Please delete it

2024-09-09 12:04 UTC, nikita-remeslov requested changes

2024-09-09 12:04 UTC, nikita-remeslov commented on frontend/src/bundles/common/icons/helper/icon-conversion.helper.ts
looks like we can avoid using `Icon` postfix

2024-09-09 21:15 UTC, o-nedashkivska approved these changes

2024-09-10 06:26 UTC, anton-otroshchenko approved these changes

2024-09-10 07:29 UTC, o-nedashkivska submitted a review, later dismissed

2024-09-10 21:39 UTC, o-nedashkivska approved these changes

2024-09-11 07:29 UTC, merged