OV-142: add player controls to studio
BinaryStudioAcademy/bsa-2024-outreachvids pull request #145
Opened 2024-09-03 19:04 UTC by Sanchousina

Also depends on [OV-110](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/137)

Added player controls component to studio page.

I found an issue with the timeline component: if there is not enough space for generated items, more rows are automatically created, and the timeline component becomes bigger. @stefano-lacorazza is working on that.

![image](https://github.com/user-attachments/assets/bdc7b9c6-309f-4183-9f1a-0d662b6b9617)

2024-09-03 19:10 UTC, closed without merging

2024-09-03 21:35 UTC, stefano-lacorazza commented
> Also depends on [OV-110](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/137)
> 
> Added player controls component to studio page.
> 
> I found an issue with the timeline component: if there is not enough space for generated items, more rows are automatically created, and the timeline component becomes bigger. @stefano-lacorazza is working on that.
> 
> ![image](https://private-user-images.githubusercontent.com/74914822/364106950-bdc7b9c6-309f-4183-9f1a-0d662b6b9617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzOTQzNzAsIm5iZiI6MTcyNTM5NDA3MCwicGF0aCI6Ii83NDkxNDgyMi8zNjQxMDY5NTAtYmRjN2I5YzYtMzA5Zi00MTgzLTlmMWEtMGQ2NjJiNmI5NjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOT

https://github.com/user-attachments/assets/d8822255-e557-445d-a3c8-4a6d1702a17b

AzVDIwMDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjY5NWI5ODQ5NmUxNjA5NTg2ZDFjYTA3ZmZmYzU4NzEyMWI1OTkyYWY3ZjQ0OGI0ZTczYTU5MDQ3MmZmN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KXYokVLw6EZcXg_gRENzUVFbvqqWB7Oos_P3atR0Nqs)

Its not that extra rows are created, if two items ocupy the same time they are stacked in top of each other in the same row. Changed row border to black so it is clear.

2024-09-04 23:34 UTC, JKaypa requested changes

2024-09-04 23:34 UTC, JKaypa commented on frontend/src/bundles/studio/components/timeline/timeline-view/timeline-view.tsx
> +import { TimeCursor } from '../timecursor/timecursor.js';
I think this should be handled in a better way, imported from one file

2024-09-04 23:34 UTC, JKaypa commented on frontend/src/bundles/studio/components/timeline/timeline-view/timeline-view.tsx
> +interface TimelineProperties {
We are using type, for consistency

2024-09-05 13:13 UTC, o-nedashkivska approved these changes

2024-09-05 13:14 UTC, anton-otroshchenko approved these changes

2024-09-05 13:15 UTC, nikita-remeslov approved these changes