OV-2: FEAT: Sign-in flow
BinaryStudioAcademy/bsa-2024-outreachvids pull request #17
Opened 2024-08-19 15:25 UTC by JKaypa

Add sign-in functionality from the backend. A data transfer object containing user credentials (email, password) is used to compare against existing data

2024-08-19 19:56 UTC, anton-otroshchenko requested changes

2024-08-19 19:56 UTC, anton-otroshchenko commented on backend/src/bundles/users/user.repository.ts
> +    public async find(payload: string | number): Promise<UserEntity | null> {
find method should only find by id.

Please create a specific method if you want to use different fields

for example findByEmail()

2024-08-20 07:54 UTC, anton-otroshchenko requested changes

2024-08-20 07:54 UTC, anton-otroshchenko commented on backend/src/common/types/repository.type.ts
> +    findByEmail(email: string): Promise<T>;
we will have this method only in user repo so there is no need to put this in type here

2024-08-20 07:54 UTC, anton-otroshchenko commented on backend/src/common/types/service.type.ts
> +    findByEmail(email: string): Promise<T>;
same here

2024-08-20 12:24 UTC, anton-otroshchenko approved these changes

2024-08-20 12:38 UTC, nikita-remeslov requested changes

2024-08-20 12:38 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.controller.ts
> +    private async signIn(
you should add js doc for endpoint

2024-08-21 09:30 UTC, nikita-remeslov approved these changes

2024-08-21 09:30 UTC, merged