Task/ov 164 remove sx prop
BinaryStudioAcademy/bsa-2024-outreachvids pull request #178
Opened 2024-09-06 01:05 UTC by stefano-lacorazza

Removed all sx props and added the styles to module.css files.

2024-09-06 01:09 UTC, stefano-lacorazza commented
Is it ok to name the module. css files as: componentName.module.css or is it better to just call them styles.module.css as each file is in its component folder?

2024-09-10 06:28 UTC, anton-otroshchenko commented
We should create styles file for each component

2024-09-10 07:17 UTC, o-nedashkivska commented on frontend/src/bundles/common/components/video-modal/components/video-modal-content/components/generate-script-form/generate-script-form.tsx
> +import styles from '../../../../video-modal.module.css';
Let's import from `~/bundles ...` here

2024-09-10 07:17 UTC, o-nedashkivska commented on frontend/src/bundles/common/components/video-modal/components/video-modal-content/components/generate-script-form/generate-script-form.tsx
> +import styles from '../../../../video-modal.module.css';
And the same for components below

2024-09-10 09:41 UTC, nikita-remeslov requested changes
all css module file should have same name `styles.module.css`

2024-09-10 21:10 UTC, o-nedashkivska submitted a review, later dismissed

2024-09-11 11:37 UTC, XCODE89 commented on frontend/src/bundles/studio/components/video-menu/components/menu/menu.module.css
menu.module.css to styles.module.css

2024-09-11 14:15 UTC, merged