OV-196: add avatar video api
BinaryStudioAcademy/bsa-2024-outreachvids pull request #199
Opened 2024-09-07 14:28 UTC by sergiy4

This PR adds avatar-api

2024-09-09 11:17 UTC, nikita-remeslov requested changes

2024-09-09 11:17 UTC, nikita-remeslov commented on backend/src/common/services/azure-ai/apis/apis.ts
why it is called `apis`?

2024-09-09 11:30 UTC, sergiy4 commented on backend/src/common/services/azure-ai/apis/apis.ts
Because there is also a tts-api.
![image](https://github.com/user-attachments/assets/93a40c8b-879f-4178-b6eb-e8a492f82dda)

2024-09-10 06:32 UTC, anton-otroshchenko requested changes

2024-09-10 06:32 UTC, anton-otroshchenko commented on backend/.env.example
> +AZURE_SERVICE_ENDPOINT=https://westeurope.api.cognitive.microsoft.com
Lets also hide it and send this info in slack

2024-09-10 07:34 UTC, o-nedashkivska submitted a review, later dismissed

2024-09-11 07:44 UTC, anton-otroshchenko approved these changes

2024-09-11 08:07 UTC, sofiia-trokhymchuk requested changes

2024-09-11 08:07 UTC, sofiia-trokhymchuk commented on backend/src/common/services/azure-ai/avatar-video/avatar-video-base.ts
> +                `${AvatarApiPath.BATCHSYNTHESES}/${id}?api-version=2024-08-01`,
Since `api-version` is a query param that is changeable it is better to move it to the constants especially if it is repeated in several places

2024-09-11 10:03 UTC, o-nedashkivska approved these changes

2024-09-11 10:21 UTC, sofiia-trokhymchuk approved these changes

2024-09-11 14:11 UTC, nikita-remeslov approved these changes

2024-09-11 14:11 UTC, merged