OV-166: Add AI icon to script menu
BinaryStudioAcademy/bsa-2024-outreachvids pull request #225
Opened 2024-09-09 22:41 UTC by JKaypa

This PR add OpenAI icon to script menu to open the chat
![image](https://github.com/user-attachments/assets/36dfe54c-e4e5-45d5-8638-219245746979)

2024-09-10 06:35 UTC, anton-otroshchenko requested changes

2024-09-10 06:35 UTC, anton-otroshchenko commented on frontend/src/bundles/studio/components/video-menu/components/menu-body/menu-body.tsx
> +                            ) : null}
```suggestion
                            {title === 'Script' && (
                                <IconButton
                                    aria-label="OpenAI icon button"
                                    icon={
                                        <Icon
                                            as={IconName.OPEN_AI}
                                            boxSize={6}
                                        />
                                    }
                                    variant="icon"
                                    onClick={onChatOpen}
                                />
                            )}
```

2024-09-10 07:46 UTC, o-nedashkivska commented on frontend/src/bundles/studio/components/video-menu/components/menu-body/menu-body.tsx
> +import { IconName } from '~/bundles/common/icons/icon-name.js';
Let's import from root file

2024-09-10 18:05 UTC, anton-otroshchenko approved these changes

2024-09-10 21:37 UTC, o-nedashkivska approved these changes

2024-09-11 13:34 UTC, nikita-remeslov approved these changes

2024-09-11 13:34 UTC, merged