OV-173: add azure avatar integration
BinaryStudioAcademy/bsa-2024-outreachvids pull request #231
Opened 2024-09-10 07:23 UTC by sergiy4

This PR adds azure avatar integration.
Depends on #199 

[1725950422610.webm](https://github.com/user-attachments/assets/b29d7cb4-3998-4e38-a925-9e9606762ec3)

![azure-post](https://github.com/user-attachments/assets/bf2d7810-7f08-4164-8bc7-00f290d3db1b)
1. POST method for rendering an avatar

![saved-file](https://github.com/user-attachments/assets/35c089eb-befa-4b5e-867b-84fcaed666f8)
2. GET videos

2024-09-10 08:20 UTC, o-nedashkivska commented on backend/src/bundles/avatar-videos/avatar-videos.service.ts
> +    public async saveAvatarVideo(url: string, id: string): Promise<string> {
```suggestion
    private async saveAvatarVideo(url: string, id: string): Promise<string> {
```

2024-09-10 08:20 UTC, o-nedashkivska commented on backend/src/bundles/avatar-videos/avatar-videos.service.ts
> +    public checkAvatarProcessing(id: string, userId: string): void {
```suggestion
    private checkAvatarProcessing(id: string, userId: string): void {
```

2024-09-10 08:20 UTC, o-nedashkivska commented on backend/src/bundles/avatar-videos/avatar-videos.service.ts
> +            id: Date.now().toString(),
Can we use uuid here for id generation?

2024-09-10 08:20 UTC, o-nedashkivska commented on backend/src/bundles/avatar-videos/avatar-videos.controller.ts
> +    }
Do we need a separate controller to get avatar video by id? I thought once it is generated we save it to videos table and then on home page just retrieve all videos and show them to user. And on frontend we will now anything about generated video id.

2024-09-11 07:13 UTC, o-nedashkivska commented on backend/src/bundles/avatar-videos/avatar-videos.service.ts
> +                });
Maybe, we can create a separate function for that and use async await so it will be more readable?

2024-09-11 07:16 UTC, o-nedashkivska commented on backend/src/bundles/avatar-videos/avatar-videos.service.ts
> +        await this.azureAIService.removeAvatarVideo(id);
```suggestion
        await this.removeAvatarVideo(id);
```

2024-09-11 08:19 UTC, sofiia-trokhymchuk requested changes

2024-09-11 08:19 UTC, sofiia-trokhymchuk commented on backend/src/bundles/avatar-videos/avatar-videos.service.ts
> +        }, 4000);
Move time delay to the constants

2024-09-11 10:23 UTC, sofiia-trokhymchuk submitted a review, later dismissed

2024-09-11 13:33 UTC, o-nedashkivska approved these changes

2024-09-11 14:11 UTC, nikita-remeslov approved these changes

2024-09-11 14:12 UTC, merged