OV-230: Replace mocked script audio with text-to-speech
BinaryStudioAcademy/bsa-2024-outreachvids pull request #236
Opened 2024-09-10 12:05 UTC by o-nedashkivska

2024-09-10 13:24 UTC, nikita-remeslov requested changes

2024-09-10 13:24 UTC, nikita-remeslov commented on frontend/src/bundles/studio/store/slice.ts
i think we should have one dataStatus for store

2024-09-10 13:43 UTC, o-nedashkivska commented on frontend/src/bundles/studio/store/slice.ts
I added dataStatus for each script because I need to show loader on play button when I send a request for text-to-speech.

2024-09-11 13:02 UTC, nikita-remeslov approved these changes

2024-09-11 13:02 UTC, merged