OV-257: Fetch user videos
BinaryStudioAcademy/bsa-2024-outreachvids pull request #265
Opened 2024-09-11 20:46 UTC by Sanchousina

Depends on [OV-233](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/245)

In this pr:
- Fetch all user videos
- Display videos on the home page
- Fixed grid for the video section (discovered that when we don't have enough elements,  they take all the available space).

![image](https://github.com/user-attachments/assets/2a665abb-00e2-4b00-a22a-4f3cc77ec45f)

2024-09-11 21:06 UTC, sergiy4 commented on frontend/src/bundles/home/components/main-content/main-content.tsx
> +    const { videos, dataStatus } = useAppSelector(({ home }) => home);
It would be better to return only the fields you need instead of returning the entire home store.

2024-09-11 21:36 UTC, o-nedashkivska commented on frontend/src/bundles/home/components/video-section/video-section.tsx
> +            {hasVideos ? (
```suggestion
            {videos.length > 0 ? (
```
I guess we can use this condition directly without creating a separate variable

2024-09-11 21:36 UTC, o-nedashkivska commented on frontend/src/bundles/home/components/video-section/video-section.tsx
> +                </Text>
Please, add custom variant for text

2024-09-11 21:36 UTC, o-nedashkivska commented on frontend/src/bundles/home/components/video-section/video-section.tsx
> +                    {videos.map((video) => (
```suggestion
                    {videos.map(({ id, name, url }) => (
```
You can use destructuring here

2024-09-12 09:36 UTC, o-nedashkivska submitted a review, later dismissed

2024-09-12 09:38 UTC, nikita-remeslov requested changes

2024-09-12 09:38 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/main-content/main-content.tsx
> +    const videos = useAppSelector(({ home }) => home.videos);
you can combine it

2024-09-12 09:52 UTC, nikita-remeslov approved these changes

2024-09-12 09:53 UTC, merged