OV-276: Add delete button for videos
BinaryStudioAcademy/bsa-2024-outreachvids pull request #292
Opened 2024-09-13 16:35 UTC by o-nedashkivska

Related issue - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/276

<img width="486" alt="Screenshot 2024-09-13 at 19 34 52" src="https://github.com/user-attachments/assets/3369208d-cd7f-4b5c-be1a-a0c2df2caa46">

2024-09-16 08:03 UTC, anton-otroshchenko submitted a review, later dismissed

2024-09-16 12:19 UTC, Sanchousina submitted a review, later dismissed

2024-09-16 13:35 UTC, sofiia-trokhymchuk submitted a review, later dismissed

2024-09-16 15:24 UTC, nikita-remeslov requested changes
we should add some warning modal before we delete the video

2024-09-17 07:00 UTC, sergiy4 submitted a review, later dismissed

2024-09-17 12:26 UTC, sofiia-trokhymchuk submitted a review, later dismissed

2024-09-17 21:41 UTC, nikita-remeslov approved these changes

2024-09-17 21:41 UTC, merged