OV-275: Add Socket Notifications For Video Ready
BinaryStudioAcademy/bsa-2024-outreachvids pull request #320
Opened 2024-09-16 23:27 UTC by lfelix3011

This PR is for this task https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/275

- [ ] Add socket for notifications so user can receive notification when video is ready

https://github.com/user-attachments/assets/3e7ba67f-5bdc-4cc7-a65c-0880f99a1a1f

2024-09-18 11:27 UTC, Alblupynos approved these changes, later dismissed

2024-09-18 14:39 UTC, anton-otroshchenko requested changes

2024-09-18 14:39 UTC, anton-otroshchenko commented on frontend/src/bundles/home/components/main-content/main-content.tsx
> +        const loadUserVideos = (): void => {
functions in component should start with handle, please change in the whole file

2024-09-19 19:49 UTC, sofiia-trokhymchuk commented
![image](https://github.com/user-attachments/assets/78977748-d8d3-4403-bbe0-2bd266e256f8)
What about Figma design?

2024-09-23 15:37 UTC, lfelix3011 commented
> ![image](https://private-user-images.githubusercontent.com/165810672/369148217-78977748-d8d3-4403-bbe0-2bd266e256f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDYwMjcsIm5iZiI6MTcyNzEwNTcyNywicGF0aCI6Ii8xNjU4MTA2NzIvMzY5MTQ4MjE3LTc4OTc3NzQ4LWQ4ZDMtNDQwMy1iYmUwLTJiZDI2NmUyNTZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxNTM1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWM5MGNjOTE5ZGQwYzBkOTM5ZmNiZjQyYTU1ZjViYzg4ODVmNGIyYjJlNDZlNjRmMjRlNDBiNzc5MzIwYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.stieGo515-cCMmT4UUi9KY5YAeyWlTfgGbCFBD9IYis) What about Figma design?

@nikita-remeslov Said comment in daily that for now we could show a toaster notification insted of the bell, thats why is been move back to peer review

2024-09-24 10:23 UTC, nikita-remeslov submitted a review, later dismissed

2024-09-25 10:21 UTC, merged