OV-307: Show Preview Url Of Each Video as Thumbnails
BinaryStudioAcademy/bsa-2024-outreachvids pull request #336
Opened 2024-09-18 02:15 UTC by lfelix3011

This PR is for this Task https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/307

![image](https://github.com/user-attachments/assets/6bf28f6b-a11b-4b1e-86e0-580d6b196235)

2024-09-18 09:40 UTC, Sanchousina commented
I already did that when working on the task: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/311

2024-09-18 09:43 UTC, Alblupynos submitted a review, later dismissed

2024-09-18 10:53 UTC, stefano-lacorazza submitted a review, later dismissed

2024-09-18 14:41 UTC, anton-otroshchenko requested changes

2024-09-18 14:41 UTC, anton-otroshchenko commented on frontend/src/bundles/home/components/video-card/video-card.tsx
> +                    src={previewUrl || photo}
please replace || with ??

2024-09-18 14:55 UTC, Sanchousina commented
Look at this commit: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/343/commits/24d5376bf3581d92c238aaa6ab29ecc0684e0a0e

2024-09-21 03:39 UTC, lfelix3011 commented
The changes made here were also done in this PR https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/343m
, as that one was already merge, this one will be closed

2024-09-21 03:40 UTC, closed without merging