OV-329: Center Resize video
BinaryStudioAcademy/bsa-2024-outreachvids pull request #338
Opened 2024-09-18 09:39 UTC by stefano-lacorazza

Centered Resize video in Studio page

https://github.com/user-attachments/assets/91295c87-55a8-42bb-b6a7-83b60dd6179d

2024-09-18 10:04 UTC, sofiia-trokhymchuk requested changes
It is better to modify the Header component and make the center item always stay in the middle rather than to hardcode the left margin
Useful link: [https://stackoverflow.com/questions/32378953/keep-the-middle-item-centered-when-side-items-have-different-widths](https://stackoverflow.com/questions/32378953/keep-the-middle-item-centered-when-side-items-have-different-widths)

2024-09-18 10:29 UTC, stefano-lacorazza commented
> It is better to modify the Header component and make the center item always stay in the middle rather than to hardcode the left margin Useful link: https://stackoverflow.com/questions/32378953/keep-the-middle-item-centered-when-side-items-have-different-widths

Thank you. Worked great

https://github.com/user-attachments/assets/fac89a07-b5cf-42cc-92dc-0069fc3e5fdb

2024-09-18 14:41 UTC, anton-otroshchenko approved these changes

2024-09-19 12:33 UTC, sergiy4 approved these changes

2024-09-19 19:36 UTC, sofiia-trokhymchuk approved these changes

2024-09-19 19:36 UTC, merged