OV-287: Add horizontal scroll in timeline
BinaryStudioAcademy/bsa-2024-outreachvids pull request #340
Opened 2024-09-18 10:57 UTC by XCODE89

- Horizontal scroll was added to the timeline.
- Range readjustment was done when deleting or resizing a scene.

2024-09-18 10:57 UTC, XCODE89 commented
![image](https://github.com/user-attachments/assets/d06453a8-c8e9-466f-8606-bb7506335e84)

2024-09-18 14:42 UTC, anton-otroshchenko requested changes

2024-09-18 14:42 UTC, anton-otroshchenko commented on frontend/src/bundles/studio/components/timeline/timeaxis/timeaxis.tsx
> +    const timelineWidth = range.end * 0.011;
fix magic value

2024-09-18 14:42 UTC, anton-otroshchenko commented on frontend/src/bundles/studio/helpers/get-total-time.ts
> +        return totalMilliseconds + 6000;
same here

2024-09-18 14:42 UTC, anton-otroshchenko commented on frontend/src/bundles/studio/helpers/get-total-time.ts
> +    return totalMilliseconds >= rangeEnd ? totalMilliseconds + 6000 : rangeEnd;
and here

2024-09-20 08:16 UTC, nikita-remeslov approved these changes

2024-09-20 08:16 UTC, merged