OV-311: Save video draft
BinaryStudioAcademy/bsa-2024-outreachvids pull request #343
Opened 2024-09-18 12:40 UTC by Sanchousina

In this pr:

- User can save video draft
- User can see when he made new changes that are not saved
- User is shown a notification for video save
- User is not allowed to save video that doesn't have at least 1 scene with an avatar and 1 script
- Video record is created on the first save and is updated on the next saves
- When the user submits a video for rendering, if it was saved previously - the video record updates, if not - a new video record is created.
- Use preview url for video thumbnails
- If the user changes the first scene avatar after saving the video, on the next save the preview url is updated as well

https://github.com/user-attachments/assets/f1e6350e-b19e-49fc-a442-2676b6ddb497

2024-09-18 14:44 UTC, anton-otroshchenko requested changes

2024-09-18 14:44 UTC, anton-otroshchenko commented on backend/src/bundles/videos/video.repository.ts
> +            data.previewUrl = payload.composition.scenes[0]?.avatar?.url || '';
please replace || with ??

2024-09-19 12:45 UTC, sergiy4 submitted a review, later dismissed

2024-09-19 19:31 UTC, sofiia-trokhymchuk requested changes

2024-09-19 19:31 UTC, sofiia-trokhymchuk commented on frontend/src/bundles/studio/components/video-name-input/video-name-input.tsx
> +        isDraftSaved ? videoName : `${videoName}*`,
You use this logic in several places. Use `useMemo`

2024-09-19 19:31 UTC, sofiia-trokhymchuk commented on frontend/src/framework/store/store.package.ts
> +} from '../../bundles/common/middlewares/middlewares.js';
Fix the import path, please

2024-09-20 11:00 UTC, nikita-remeslov approved these changes, later dismissed

2024-09-20 11:22 UTC, nikita-remeslov approved these changes

2024-09-20 11:22 UTC, merged