OV-352: Add logic for edit video button
BinaryStudioAcademy/bsa-2024-outreachvids pull request #357
Opened 2024-09-19 11:29 UTC by Sanchousina

Depends on [OV-311 ](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/343)

In this pr:

When user clicks on edit video button, the studio page opens with loaded video data.

https://github.com/user-attachments/assets/de94d48b-98c7-4e0f-9a38-182cdf936d8f

2024-09-19 19:34 UTC, sofiia-trokhymchuk requested changes

2024-09-19 19:34 UTC, sofiia-trokhymchuk commented on backend/src/bundles/videos/video.repository.ts
> +                composition: composition,
Why can't you use just `composition`?

2024-09-19 19:34 UTC, sofiia-trokhymchuk commented on backend/src/bundles/videos/video.repository.ts
Why delete empty lines everywhere? :)

2024-09-19 19:34 UTC, sofiia-trokhymchuk commented on backend/src/bundles/videos/video.service.ts
>                  previewUrl: payload.composition?.scenes[0]?.avatar?.url || '',
```suggestion
                previewUrl: payload.composition?.scenes[0]?.avatar?.url ?? '',
```

2024-09-20 11:32 UTC, nikita-remeslov approved these changes

2024-09-20 11:32 UTC, merged