OV-347: Connect Generate Script With Studio Page
BinaryStudioAcademy/bsa-2024-outreachvids pull request #381
Opened 2024-09-21 03:35 UTC by lfelix3011

This PR is for this task https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/347

Important Notes: Properties isVideoScriptsGenerationPending / isVideoScriptsGenerationReady of studio state was made, cause need it a way to know when the addGeneratedVideoScript begin and when it ends that way can trigger  the others actions and know when to show and hide the Overlay

Evidence
https://github.com/user-attachments/assets/77360b53-2b83-4f9a-b678-7710ee4115f3

2024-09-23 14:37 UTC, anton-otroshchenko requested changes

2024-09-23 14:37 UTC, anton-otroshchenko commented on frontend/src/bundles/chat/store/slice.ts
lets prevent magic values in this file because we will have to fix them on the second quality criteria check

2024-09-23 14:37 UTC, anton-otroshchenko commented on frontend/src/bundles/studio/store/slice.ts
> +                    //This if is cause we have already one scene at the begging
please remove the comment

2024-09-24 10:22 UTC, nikita-remeslov submitted a review, later dismissed

2024-09-26 12:22 UTC, anton-otroshchenko approved these changes, later dismissed

2024-09-26 14:08 UTC, sofiia-trokhymchuk approved these changes

2024-09-26 14:09 UTC, merged