OV-391: add logic to delete video
BinaryStudioAcademy/bsa-2024-outreachvids pull request #395
Opened 2024-09-23 21:04 UTC by sergiy4

This PR adds the logic to delete a rendered video from the Remotion S3 bucket

2024-09-24 08:41 UTC, sofiia-trokhymchuk requested changes

2024-09-24 08:41 UTC, sofiia-trokhymchuk commented on backend/src/bundles/videos/video.service.ts
> +            if (renderIdMatch && renderIdMatch[1]) {
Use a descriptive const for `renderIdMatch[1]` since you use it twice

2024-09-26 12:23 UTC, anton-otroshchenko approved these changes

2024-09-26 13:58 UTC, sofiia-trokhymchuk approved these changes

2024-09-26 13:58 UTC, merged