OV-377: Create preview page and flow
BinaryStudioAcademy/bsa-2024-outreachvids pull request #429
Opened 2024-09-25 14:11 UTC by stefano-lacorazza

### Summary:
This pull request implements the following features:

1. **Preview Page Creation**:  
   - Created a whitelisted separate Preview page, accessible via a generated JWT-based URL.
   - Added a video player to this page for playback of the video.

2. **Button for Generating Preview Link**:  
   - Added a button to each rendered video on the homepage to copy the preview link.
   - When the button is clicked, a request is sent to the backend to generate a JWT containing the video ID.

3. **JWT-based Preview URL Generation**:  
   - Added an endpoint to generate a preview URL with a JWT and the videoId.  
   - The server response returns a URL string with the format `preview/:jwt`, which includes the JWT and the video ID.
   - Upon receiving the server response, the preview URL is copied to the clipboard.

4. **Preview URL Access and JWT Decoding**:  
   - When a user accesses the preview URL, the JWT and videoId are extracted from the page URL.
   - A request is sent to decode the JWT and retrieve the videoId.
   - The decoded videoId is then used to fetch the corresponding video URL for playback.

5. **New Public-Video Controller**:  
   - Implemented a new `public-video` controller to handle requests related to video previews, including decoding JWTs and retrieving video information.

https://github.com/user-attachments/assets/9b5c8b7d-5fb2-43fc-9c41-9bb668c8b24b

---

2024-09-25 14:14 UTC, stefano-lacorazza commented on frontend/src/bundles/home/helpers/create-url-token.ts
> +    const baseUrl = 'http://localhost:3000';
Here how could I create the baseUrl dynamically for deployment?

2024-09-26 12:29 UTC, anton-otroshchenko requested changes

2024-09-26 12:29 UTC, anton-otroshchenko commented on backend/src/common/services/token/token.services.ts
> +
lets move it to video service

2024-09-26 12:29 UTC, anton-otroshchenko commented on backend/src/common/services/token/token.services.ts
> +
can we use createToken method and set expiration time optional?

2024-09-26 12:29 UTC, anton-otroshchenko commented on backend/src/common/services/token/token.services.ts
> +        return (payload?.['videoId'] as string) || null;
```suggestion
        return (payload?.['videoId'] as string) ?? null;
```

2024-09-26 12:29 UTC, anton-otroshchenko commented on frontend/src/bundles/preview/pages/preview.tsx
> +    const [loading, setLoading] = useState<boolean>(true);
isLoading, setIsLoading

2024-09-26 13:50 UTC, anton-otroshchenko requested changes

2024-09-26 13:50 UTC, anton-otroshchenko commented on frontend/src/bundles/home/helpers/create-url-token.ts
> +        import.meta.env['VITE_APP_NODE_ENV'] === 'production'
please use our class on frontend to handle .env

2024-09-26 13:50 UTC, anton-otroshchenko commented on frontend/src/bundles/home/helpers/create-url-token.ts
> +        import.meta.env['VITE_APP_NODE_ENV'] === 'production'
also use this 
<img width="487" alt="image" src="https://github.com/user-attachments/assets/1049799c-23cc-4f4a-8047-d6a7549900ba">

2024-09-26 14:36 UTC, sofiia-trokhymchuk requested changes

2024-09-26 14:36 UTC, sofiia-trokhymchuk commented on frontend/src/bundles/home/helpers/create-url-token.ts
> +
Add a new env variable and use it. What if the deployment URL changes?

2024-09-26 14:36 UTC, sofiia-trokhymchuk commented on backend/src/bundles/public-video/public-video.controller.ts
> +                videoTokenHeader ?? '',
Why do you need this nullish coalescing here? You already check it on line 32

2024-09-26 14:36 UTC, sofiia-trokhymchuk commented on backend/src/bundles/public-video/public-video.service.ts
> +        const url = video.toObject().url;
```suggestion
        const { url } = video.toObject();
```

2024-09-26 14:36 UTC, sofiia-trokhymchuk commented on backend/src/bundles/videos/video.controller.ts
> +            path: `${VideosApiPath.ID}/share`,
Add this path to the enum

2024-09-26 14:36 UTC, sofiia-trokhymchuk commented on frontend/src/bundles/common/api/video-api/videos-api.ts
> +            this.getFullEndpoint(`${VideosApiPath.ROOT}${id}/share`, {}),
Same here

2024-09-26 15:14 UTC, stefano-lacorazza commented on frontend/src/bundles/home/helpers/create-url-token.ts
> +
Done but could you test it if it was done correctly before merging? I have no way of testing in production enviroment and I dont want to break something a day before the demo. Thank you

2024-09-26 17:21 UTC, sofiia-trokhymchuk requested changes

2024-09-26 17:21 UTC, sofiia-trokhymchuk commented on frontend/src/bundles/home/helpers/create-url-token.ts
> +            ? config.ENV.DEPLOYMENT.URL
It is better to add something like PUBLIC_URL. And use it as it is without checks

2024-09-26 17:21 UTC, sofiia-trokhymchuk commented on frontend/.env.example
> +DEPLOYMENT_URL=http://bsa-2024-outreachvids-dev.eu-north-1.elasticbeanstalk.com
```suggestion
#
# DEPLOYMENT
#
PUBLIC_URL=http://localhost:3000
```

2024-09-26 19:01 UTC, stefano-lacorazza commented on frontend/src/bundles/home/helpers/create-url-token.ts
> +            ? config.ENV.DEPLOYMENT.URL
Im having problems with this one. I changed .env,  EnvironmentSchema, and base-config.package adding the new ENV PUBLIC_URL variable but when I try to access it in createVideoUrl I keep getting undefined.

2024-09-27 10:07 UTC, sofiia-trokhymchuk approved these changes

2024-09-27 10:11 UTC, nikita-remeslov approved these changes

2024-09-27 10:12 UTC, merged