OV-369: Implement create avatar flow
BinaryStudioAcademy/bsa-2024-outreachvids pull request #433
Opened 2024-09-25 17:18 UTC by stefano-lacorazza

Implemented flow between, instructions, upload and consent components

https://github.com/user-attachments/assets/17674b5b-dd45-4841-b810-cccb8dfa4f30

2024-09-26 12:31 UTC, anton-otroshchenko requested changes

2024-09-26 12:31 UTC, anton-otroshchenko commented on frontend/src/bundles/create-avatar/pages/create-avatar.tsx
> +    const steps = useMemo(() => ['Instructions', 'Upload', 'Consent'], []);
can we create object for this values because you reuse them a lot

2024-09-26 14:10 UTC, sofiia-trokhymchuk requested changes

2024-09-26 14:10 UTC, sofiia-trokhymchuk commented on frontend/src/bundles/common/components/stepper/stepper.tsx
>      const progressPercent = (activeStepIndex / (steps.length - 1)) * 100;
Magic numbers

2024-09-26 17:15 UTC, sofiia-trokhymchuk requested changes

2024-09-26 17:15 UTC, sofiia-trokhymchuk commented on frontend/src/bundles/common/components/stepper/stepper.tsx
> +    const MAX_PERCENT = 100;
It is better to declare the constants outside of the component. Not necessary in an external file but outside of the component

2024-09-27 09:57 UTC, anton-otroshchenko requested changes

2024-09-27 09:57 UTC, anton-otroshchenko commented on frontend/src/bundles/create-avatar/components/instruction/instruction.tsx
> +type InstructionProperties = {
```suggestion
type Properties = {
```

2024-09-27 10:04 UTC, nikita-remeslov approved these changes

2024-09-27 10:05 UTC, merged