Task/ov 405 create templates page
BinaryStudioAcademy/bsa-2024-outreachvids pull request #440
Opened 2024-09-26 10:00 UTC by XCODE89

![image](https://github.com/user-attachments/assets/5326d510-97d2-4e44-91dc-24cf7418b79d)

2024-09-26 12:34 UTC, anton-otroshchenko approved these changes, later dismissed

2024-09-26 14:23 UTC, sofiia-trokhymchuk approved these changes

2024-09-26 14:24 UTC, sofiia-trokhymchuk requested changes
Merge conflicts

2024-09-26 17:13 UTC, sofiia-trokhymchuk approved these changes

2024-09-27 06:46 UTC, nikita-remeslov approved these changes

2024-09-27 06:46 UTC, merged