OV-39: integrate Open AI
BinaryStudioAcademy/bsa-2024-outreachvids pull request #53
Opened 2024-08-22 10:37 UTC by sergiy4

This PR adds Open AI integration.
![openai1](https://github.com/user-attachments/assets/45dbeae8-573f-4aa6-91b6-0064bc6bbed5)
![openai2](https://github.com/user-attachments/assets/7d6be007-a0f3-4145-af4f-70b435648f5b)

2024-08-22 17:46 UTC, Sanchousina commented on backend/src/common/services/open-ai/open-ai.service.ts
> +        return { generatedText };
Why not return just a string and not an object with a string, like if even from the name it says it returns text - which is string?

2024-08-22 22:37 UTC, WilsonBravo approved these changes

2024-08-26 11:23 UTC, o-nedashkivska approved these changes

2024-08-27 12:54 UTC, nikita-remeslov requested changes

2024-08-27 12:54 UTC, nikita-remeslov commented on backend/src/bundles/open-ai/libs/constants/chat-model.constant.ts
> +const CHAT_MODEL = 'gpt-4o-mini' as const;
as const we use for Enums

2024-08-27 12:54 UTC, nikita-remeslov commented on backend/src/bundles/open-ai/libs/constants/max-token.constant.ts
> +const MAX_TOKEN = 2048 as const;
the same

2024-08-27 12:54 UTC, nikita-remeslov commented on backend/src/bundles/open-ai/open-ai.service.ts
> +        return { generatedText };
why we need return object?

2024-08-27 12:54 UTC, nikita-remeslov commented on backend/src/bundles/open-ai/open-ai.service.ts
![image](https://github.com/user-attachments/assets/5f4575e9-bfaf-4757-8b25-0b4574e02c87)
looks like it works like this

2024-08-27 14:25 UTC, Sanchousina approved these changes

2024-08-28 10:02 UTC, anton-otroshchenko approved these changes

2024-08-28 10:04 UTC, nikita-remeslov approved these changes

2024-08-28 10:04 UTC, merged