Task/ov 38 add homepage
BinaryStudioAcademy/bsa-2024-outreachvids pull request #57
Opened 2024-08-22 17:10 UTC by Sanchousina

Issue #38 FEAT: Add Homepage

Created Homepage with a Video components.
Mocked the data for now.

![image](https://github.com/user-attachments/assets/13065bca-fdb0-482b-a1d6-8b363e390536)
![image](https://github.com/user-attachments/assets/3b77d8be-e9d3-40a7-9f2f-210853e9e63a)
![image](https://github.com/user-attachments/assets/c5080dd9-7ae5-4972-9d29-5526ec1ba52d)
![image](https://github.com/user-attachments/assets/713560e0-b410-415f-bdcb-eee84dadb84c)

2024-08-22 19:22 UTC, o-nedashkivska commented on frontend/src/bundles/home/pages/home.tsx
> +        </>
I think we don't need this fragment wrapper as we have only one child.

2024-08-22 19:26 UTC, o-nedashkivska commented on frontend/src/bundles/home/components/video-section/video-section.tsx
> +                    </Box>
Maybe, it will be better to use Badge component instead of Box?
https://v2.chakra-ui.com/docs/components/badge

2024-08-22 19:28 UTC, o-nedashkivska commented on frontend/src/bundles/home/components/video-card/icon-component.tsx
> +import { Flex, Icon } from '@chakra-ui/react';
You should export components from '~/bundles/common/components/components.js'

2024-08-22 19:29 UTC, o-nedashkivska commented on frontend/src/bundles/home/pages/home.tsx
> +        </>
And for other components as well

2024-08-23 09:39 UTC, nikita-remeslov requested changes

2024-08-23 09:39 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/main-content/main-content.tsx
> +import { Box } from '@chakra-ui/react';
if you import components outside common bundle, it should imported from components.ts

2024-08-23 09:39 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/video-card/video-card.tsx
> +import { Box, Flex, Image, Text } from '@chakra-ui/react';
the same

2024-08-23 09:39 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/video-card/video-card.tsx
> +import { faEllipsisVertical, faPen } from '@fortawesome/free-solid-svg-icons';
make icon folder in common bundle for FA icons

2024-08-23 09:39 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/video-card/icon-component.tsx
can we use this component in another places?

2024-08-23 09:39 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/video-section/video-section.tsx
> +import { Box, Flex, Heading, SimpleGrid } from '@chakra-ui/react';
the same

2024-08-23 09:39 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/video-section/video-section.tsx
> +import { VideoCard } from '../video-card/video-card.js';
```suggestion
import { VideoCard } from '../components.js';
```

2024-08-23 09:39 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/components.ts
export all component that you have in this folder

2024-08-23 13:58 UTC, Sanchousina commented on frontend/src/bundles/home/components/components.ts
Okay, will do. I just thought I need to export only components that are used outside of the components folder.

2024-08-23 15:07 UTC, Sanchousina commented on frontend/src/bundles/home/components/video-card/icon-component.tsx
I realized that I essentially recreated the IconButton component from chakra, so I deleted my custom component and used IconButton with additional styles

2024-08-26 08:34 UTC, o-nedashkivska submitted a review, later dismissed

2024-08-27 12:45 UTC, nikita-remeslov commented on frontend/src/bundles/home/components/video-section/video-section.tsx
> +                <VideoCard />
leave comment that is mocked data, and we need to update it

2024-08-28 10:03 UTC, anton-otroshchenko approved these changes

2024-08-28 10:06 UTC, nikita-remeslov approved these changes

2024-08-28 10:06 UTC, merged